<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BotCore\BotCore.csproj" />
    <ProjectReference Include="..\LoboForge.TNOIRC.Shared\LoboForge.TNOIRC.Shared.csproj" />
  </ItemGroup>

</Project>
